//! SeaORM Entity. Generated by sea-orm-codegen 0.1.2

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "seos"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub id: Uuid,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub product_id: Option<Uuid>,
    pub auto: Option<bool>,
    pub page_title: Option<String>,
    pub description: Option<String>,
    pub tags: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreatedAt,
    UpdatedAt,
    ProductId,
    Auto,
    PageTitle,
    Description,
    Tags,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::CreatedAt => ColumnType::Timestamp.def(),
            Self::UpdatedAt => ColumnType::Timestamp.def().null(),
            Self::ProductId => ColumnType::Uuid.def().null(),
            Self::Auto => ColumnType::Boolean.def().null(),
            Self::PageTitle => ColumnType::String(None).def().null(),
            Self::Description => ColumnType::String(None).def().null(),
            Self::Tags => ColumnType::Custom("array".to_owned()).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            _ => panic!("No RelationDef"),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
